//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap category_16 {
            get {
                object obj = ResourceManager.GetObject("category_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cvs {
            get {
                object obj = ResourceManager.GetObject("cvs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory {
            get {
                object obj = ResourceManager.GetObject("directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory_opened {
            get {
                object obj = ResourceManager.GetObject("directory_opened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap escargot {
            get {
                object obj = ResourceManager.GetObject("escargot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap escargot_small {
            get {
                object obj = ResourceManager.GetObject("escargot_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap number {
            get {
                object obj = ResourceManager.GetObject("number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap poignee {
            get {
                object obj = ResourceManager.GetObject("poignee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.43 (05/11/12):
        ///Add the possibility to delete a node with a right click of the mouse.
        ///
        ///1.0.0.42 (05/11/12):
        ///Show also the date of the oldest file.
        ///
        ///1.0.0.41 (22/03/12):
        ///Align language/extensions according to RSM and UCC rules.
        ///
        ///1.0.0.40 (22/03/12):
        ///Add drag and drop capability to count a directory.
        ///
        ///1.0.0.39 (12/10/11):
        ///Fix bug when showing oldest file of empty directory.
        ///
        ///1.0.0.38 (12/08/11):
        ///Update the ToolTrip content.
        ///
        ///1.0.0.37 (11/08/11):
        ///Add Delphi language.
        ///
        ///1.0.0.36 (10/08/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Revisions {
            get {
                return ResourceManager.GetString("Revisions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SearchDirectory {
            get {
                object obj = ResourceManager.GetObject("SearchDirectory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap size {
            get {
                object obj = ResourceManager.GetObject("size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Splash_small {
            get {
                object obj = ResourceManager.GetObject("Splash_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash_yellow {
            get {
                object obj = ResourceManager.GetObject("splash_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash_yellow_small {
            get {
                object obj = ResourceManager.GetObject("splash_yellow_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
